name: My Workflow

on:
  push:
    branches:
      - master

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print input value
        run: echo "The 'my_input_value' value is ${{ github.event.inputs.my_input_value }}"
      - name: Do something
        run: echo "Doing something ..."
        
